---
title: "Prediction Assignment"
author: "Charles Yoo"
date: "June 25, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
```

## Get the data
```{r}
trainingData <- read.csv("pml-training.csv")
testingData <- read.csv("pml-testing.csv")
```

## Examine the data
```{r}
head(trainingData)
```

## Find missing and predictor variables
```{r}
isMissing <- sapply(testingData, function (x) any(is.na(x) | x == ""))
isPredictor <- !isMissing & grepl("belt|[^(fore)]arm|dumbbell|forearm", names(isMissing))
predictors <- names(isMissing)[isPredictor]

# subset to predictors and classe
vars <- c("classe", predictors)
data <- trainingData[, vars]
trainingData <- trainingData[, classe := factor(trainingData[, classe])]
```

## References

http://www.danielemaasit.com/MachineLearning/predictionAssignment.html  
http://fss14142.github.io/CourseraMachineLearningProject/project.html  
http://flyingdisc.github.io/practical-machine-learning/
https://github.com/Xiaodan/Coursera-PML-Quantified-Self-Project/blob/gh-pages/report.Rmd
https://rpubs.com/mjtardelli/PracticalMachineLearning
https://rpubs.com/DIM302/PracticalMachineLearning
https://rstudio-pubs-static.s3.amazonaws.com/29426_041c5ccb9a6a4bedb204e33144bb0ad4.html